# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsp_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # MyBatis-Plus 配置
  mybatis-plus:
    configuration:
      # 开启驼峰命名转换
      map-underscore-to-camel-case: true

server:
  port: 8080 # 服务端口
